// Code generated by MockGen. DO NOT EDIT.
// Source: currency.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/vctrl/currency-service/currency/internal/dto"
	repository "github.com/vctrl/currency-service/currency/internal/repository"
)

// MockCurrencyRepository is a mock of CurrencyRepository interface.
type MockCurrencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyRepositoryMockRecorder
}

// MockCurrencyRepositoryMockRecorder is the mock recorder for MockCurrencyRepository.
type MockCurrencyRepositoryMockRecorder struct {
	mock *MockCurrencyRepository
}

// NewMockCurrencyRepository creates a new mock instance.
func NewMockCurrencyRepository(ctrl *gomock.Controller) *MockCurrencyRepository {
	mock := &MockCurrencyRepository{ctrl: ctrl}
	mock.recorder = &MockCurrencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyRepository) EXPECT() *MockCurrencyRepositoryMockRecorder {
	return m.recorder
}

// FindInInterval mocks base method.
func (m *MockCurrencyRepository) FindInInterval(ctx context.Context, dto *dto.CurrencyRequestDTO) ([]repository.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInInterval", ctx, dto)
	ret0, _ := ret[0].([]repository.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInInterval indicates an expected call of FindInInterval.
func (mr *MockCurrencyRepositoryMockRecorder) FindInInterval(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInInterval", reflect.TypeOf((*MockCurrencyRepository)(nil).FindInInterval), ctx, dto)
}

// Save mocks base method.
func (m *MockCurrencyRepository) Save(ctx context.Context, date time.Time, baseCurrency string, rates map[string]float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, date, baseCurrency, rates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCurrencyRepositoryMockRecorder) Save(ctx, date, baseCurrency, rates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCurrencyRepository)(nil).Save), ctx, date, baseCurrency, rates)
}

// UpdateRate mocks base method.
func (m *MockCurrencyRepository) UpdateRate(ctx context.Context, dto *dto.UpdateCurrencyRequestDTO) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRate", ctx, dto)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRate indicates an expected call of UpdateRate.
func (mr *MockCurrencyRepositoryMockRecorder) UpdateRate(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRate", reflect.TypeOf((*MockCurrencyRepository)(nil).UpdateRate), ctx, dto)
}
