server:
  port: ":8080"

auth:
  base_url: "http://auth:8080"

grpc:
  currency_service_url: "currency:8090"

password:
  global_salt: changeit
  min_size: 6
  max_size: 20
  required_symbols_regexp: "([A-Za-z].*\\d|\\d.*[A-Za-z])"
  required_symbols_hint: "password must contain latin letters and digits"

database:
  host: "postgres"
  port: 5432
  user: "admin"
  password: "password"
  name: "gateway_db"
