// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/currency/currency_service.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	DateFrom      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateRequest) Reset() {
	*x = GetRateRequest{}
	mi := &file_proto_currency_currency_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRequest) ProtoMessage() {}

func (x *GetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRequest.ProtoReflect.Descriptor instead.
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetRateRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetRateRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

type GetRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Rates         []*RateRecord          `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateResponse) Reset() {
	*x = GetRateResponse{}
	mi := &file_proto_currency_currency_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateResponse) ProtoMessage() {}

func (x *GetRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateResponse.ProtoReflect.Descriptor instead.
func (*GetRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetRateResponse) GetRates() []*RateRecord {
	if x != nil {
		return x.Rates
	}
	return nil
}

type RateRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Rate          float32                `protobuf:"fixed32,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateRecord) Reset() {
	*x = RateRecord{}
	mi := &file_proto_currency_currency_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRecord) ProtoMessage() {}

func (x *RateRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRecord.ProtoReflect.Descriptor instead.
func (*RateRecord) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_service_proto_rawDescGZIP(), []int{2}
}

func (x *RateRecord) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *RateRecord) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type UpdateRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	RateRecord    *RateRecord            `protobuf:"bytes,2,opt,name=rateRecord,proto3" json:"rateRecord,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRateRequest) Reset() {
	*x = UpdateRateRequest{}
	mi := &file_proto_currency_currency_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRateRequest) ProtoMessage() {}

func (x *UpdateRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateRateRequest) GetRateRecord() *RateRecord {
	if x != nil {
		return x.RateRecord
	}
	return nil
}

var File_proto_currency_currency_service_proto protoreflect.FileDescriptor

const file_proto_currency_currency_service_proto_rawDesc = "" +
	"\n" +
	"%proto/currency/currency_service.proto\x12\bcurrency\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x01\n" +
	"\x0eGetRateRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x127\n" +
	"\tdate_from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateFrom\x123\n" +
	"\adate_to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06dateTo\"Y\n" +
	"\x0fGetRateResponse\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12*\n" +
	"\x05rates\x18\x02 \x03(\v2\x14.currency.RateRecordR\x05rates\"P\n" +
	"\n" +
	"RateRecord\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x02R\x04rate\"e\n" +
	"\x11UpdateRateRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x124\n" +
	"\n" +
	"rateRecord\x18\x02 \x01(\v2\x14.currency.RateRecordR\n" +
	"rateRecord2\x94\x01\n" +
	"\x0fCurrencyService\x12>\n" +
	"\aGetRate\x12\x18.currency.GetRateRequest\x1a\x19.currency.GetRateResponse\x12A\n" +
	"\n" +
	"UpdateRate\x12\x1b.currency.UpdateRateRequest\x1a\x16.google.protobuf.EmptyB\x0eZ\fpkg/currencyb\x06proto3"

var (
	file_proto_currency_currency_service_proto_rawDescOnce sync.Once
	file_proto_currency_currency_service_proto_rawDescData []byte
)

func file_proto_currency_currency_service_proto_rawDescGZIP() []byte {
	file_proto_currency_currency_service_proto_rawDescOnce.Do(func() {
		file_proto_currency_currency_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_currency_currency_service_proto_rawDesc), len(file_proto_currency_currency_service_proto_rawDesc)))
	})
	return file_proto_currency_currency_service_proto_rawDescData
}

var file_proto_currency_currency_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_currency_currency_service_proto_goTypes = []any{
	(*GetRateRequest)(nil),        // 0: currency.GetRateRequest
	(*GetRateResponse)(nil),       // 1: currency.GetRateResponse
	(*RateRecord)(nil),            // 2: currency.RateRecord
	(*UpdateRateRequest)(nil),     // 3: currency.UpdateRateRequest
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_proto_currency_currency_service_proto_depIdxs = []int32{
	4, // 0: currency.GetRateRequest.date_from:type_name -> google.protobuf.Timestamp
	4, // 1: currency.GetRateRequest.date_to:type_name -> google.protobuf.Timestamp
	2, // 2: currency.GetRateResponse.rates:type_name -> currency.RateRecord
	4, // 3: currency.RateRecord.date:type_name -> google.protobuf.Timestamp
	2, // 4: currency.UpdateRateRequest.rateRecord:type_name -> currency.RateRecord
	0, // 5: currency.CurrencyService.GetRate:input_type -> currency.GetRateRequest
	3, // 6: currency.CurrencyService.UpdateRate:input_type -> currency.UpdateRateRequest
	1, // 7: currency.CurrencyService.GetRate:output_type -> currency.GetRateResponse
	5, // 8: currency.CurrencyService.UpdateRate:output_type -> google.protobuf.Empty
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_currency_currency_service_proto_init() }
func file_proto_currency_currency_service_proto_init() {
	if File_proto_currency_currency_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_currency_currency_service_proto_rawDesc), len(file_proto_currency_currency_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currency_currency_service_proto_goTypes,
		DependencyIndexes: file_proto_currency_currency_service_proto_depIdxs,
		MessageInfos:      file_proto_currency_currency_service_proto_msgTypes,
	}.Build()
	File_proto_currency_currency_service_proto = out.File
	file_proto_currency_currency_service_proto_goTypes = nil
	file_proto_currency_currency_service_proto_depIdxs = nil
}
