syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

package currency;

option go_package = "pkg/currency";

service CurrencyService {
  rpc GetRate(GetRateRequest) returns (GetRateResponse);
  rpc UpdateRate(UpdateRateRequest) returns (google.protobuf.Empty);
}

message GetRateRequest {
  string currency = 1;
  google.protobuf.Timestamp date_from = 2;
  google.protobuf.Timestamp date_to = 3;
}

message GetRateResponse {
  string currency = 1;
  repeated RateRecord rates = 2;
}

message RateRecord {
  google.protobuf.Timestamp date = 1;
  float rate = 2;
}

message UpdateRateRequest {
  string currency = 1;
  RateRecord rateRecord = 2;
}

// Тип decimal
// https://github.com/googleapis/googleapis/blob/master/google/type/decimal.proto
// https://github.com/googleapis/googleapis/blob/master/google/type/money.proto